# Name of this workflow
name: Build-Test
# Name of this run
run-name: ${{ github.actor }} Building and Testing
# When this action will be trigger
# I want to do this when we push new change with tag.
# This tag will be used next when we build and push the image to dockerhub
on:
  push:
    tags:
      - 'v*'
# There can be multiple jobs
jobs:
  # Job name
  build:
    # Target machine that this job will run on.
    # ubuntu-latest or ubuntu-22.04 is the same image (as is August 2023)
    runs-on: ubuntu-latest
    # Tasks, specify in list.
    steps:
      # https://github.com/actions/checkout: will clone Git into the image
      - uses: actions/checkout@v4
      # Execute terminal command.
      - name: Build the Docker image
        run: docker compose build
      - name: Compose up
        run: docker compose up -d
      # Execute pytest
      - name: Testing
        run: docker compose exec -it dash pytest -v
      # If the testing pass, upload the image
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Your image name
          images: akraradets/ait-ml-dash
          tags: type=semver,pattern={{version}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}